---
title: "02_Data_Visualization"
author: "Keqi YUE"
date: '2022-12-08'
output: html_document
---
## box plot for the distribution of monthly mean temperature and total rainfall during 2010 to 2022 August
```{r}
# mean temperature
ggplot(df, aes(x = month, y = Meantemp))+
  geom_boxplot(outlier.shape = NA)+
  geom_point(aes(col=Period, size = Period), position = "jitter")+
  scale_size_manual(values=c(1.5, 4, 4, 4))+
  theme_classic()+
  labs(x = "Month",
       y = "Mean Temperature (°C)")+
  theme(axis.text = element_text(size = 15),
        axis.title = element_text(size = 15),
        legend.text = element_text(size = 15),
        legend.title = element_text(size = 15))+
  facet_wrap( ~ District)
```

```{r}
# total rainfall
ggplot(df, aes(x = month, y = Totalrain))+
  geom_boxplot(outlier.shape = NA)+
  geom_point(aes(col=Period, size = Period), position = "jitter")+
  scale_size_manual(values=c(1.5, 4, 4, 4))+
  theme_classic()+
  labs(x = "Month",
       y = "Monthly total rainfall (mm)")+
  theme(axis.text = element_text(size = 15),
        axis.title = element_text(size = 15),
        legend.text = element_text(size = 15),
        legend.title = element_text(size = 15))+
  facet_wrap( ~ District)
```

